# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

parameters:
  - name: qaTest
    displayName: Run QA Tests?
    type: boolean
    default: true 
  - name: stgTest
    displayName: Run STG Tests?
    type: boolean
    default: false 
  - name: PDGM_ICD10_Validation
    type: boolean
    default: false 
  - name: HH_ReportAdmin
    type: boolean
    default: false 
  - name: CompanyMileage_HH_EntityAddress
    type: boolean
    default: false 
  - name: CompanyMileage_HH_Trip
    type: boolean
    default: false 
  - name: CompanyMileage_HH_User
    type: boolean
    default: false 
  - name: CompanyMileage_HHH
    type: boolean
    default: false 
  - name: CompanyMileage_KH_EntityAddress
    type: boolean
    default: false 
  - name: CompanyMileage_KH_Trip
    type: boolean
    default: false 
  - name: CompanyMileage_KH_User
    type: boolean
    default: false 
  - name: Playmaker_KH
    type: boolean
    default: false 

variables:
  ${{ if eq( parameters.PDGM_ICD10_Validation, true ) }}:
    PDGM_ICD10_Validation: TestCategory=PDGM_ICD10_Validation|
  ${{ if eq( parameters.HH_ReportAdmin, true ) }}:
    HH_ReportAdmin: TestCategory=HH_ReportAdmin|
  ${{ if eq( parameters.CompanyMileage_HH_EntityAddress, true ) }}:
    CompanyMileage_HH_EntityAddress: TestCategory=CompanyMileage_HH_EntityAddress|
  ${{ if eq( parameters.CompanyMileage_HH_Trip, true ) }}:
    CompanyMileage_HH_Trip: TestCategory=CompanyMileage_HH_Trip|
  ${{ if eq( parameters.CompanyMileage_HH_User, true ) }}:
    CompanyMileage_HH_User: TestCategory=CompanyMileage_HH_User|
  ${{ if eq( parameters.CompanyMileage_HHH, true ) }}:
    CompanyMileage_HHH: TestCategory=CompanyMileage_HHH|
  ${{ if eq( parameters.CompanyMileage_KH_EntityAddress, true ) }}:
    CompanyMileage_KH_EntityAddress: TestCategory=CompanyMileage_KH_EntityAddress|
  ${{ if eq( parameters.CompanyMileage_KH_Trip, true ) }}:
    CompanyMileage_KH_Trip: TestCategory=CompanyMileage_KH_Trip|
  ${{ if eq( parameters.CompanyMileage_KH_User, true ) }}:
    CompanyMileage_KH_User: TestCategory=CompanyMileage_KH_User|
  ${{ if eq( parameters.HH_ReportAdPlaymaker_KHmin, true ) }}:
    Playmaker_KH: TestCategory=Playmaker_KH|

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo ${{ variables.PDGM_ICD10_Validation }}${{ variables.HH_ReportAdmin }}${{ variables.CompanyMileage_HH_EntityAddress }}${{ variables.CompanyMileage_HH_Trip }}${{ variables.CompanyMileage_HH_User }}${{ variables.CompanyMileage_HHH }}${{ variables.CompanyMileage_KH_EntityAddress }}${{ variables.CompanyMileage_KH_Trip }}${{ variables.CompanyMileage_KH_User }}${{ variables.Playmaker_KH }}
