# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

parameters:
  - name: qaTest
    displayName: Run QA Tests?
    type: boolean
    default: true 
  - name: stgTest
    displayName: Run STG Tests?
    type: boolean
    default: false 
  - name: PDGM_ICD10_Validation
    type: boolean
    default: false 
  - name: HH_ReportAdmin
    type: boolean
    default: false 
  - name: CompanyMileage_HH_EntityAddress
    type: boolean
    default: false 
  - name: CompanyMileage_HH_Trip
    type: boolean
    default: false 
  - name: CompanyMileage_HH_User
    type: boolean
    default: false 
  - name: CompanyMileage_HHH
    type: boolean
    default: false 
  - name: CompanyMileage_KH_EntityAddress
    type: boolean
    default: false 
  - name: CompanyMileage_KH_Trip
    type: boolean
    default: false 
  - name: CompanyMileage_KH_User
    type: boolean
    default: false 
  - name: Playmaker_KH
    type: boolean
    default: false 


